/*
 * 
 * Copyright (C) 2015 Éric Wenaas
 * 
 */
package ca.qc.bdeb.hexknight.ui;

import ca.qc.bdeb.hexknight.commun.Personnage;

/**
 * Classe qui permet de choisir les options pour la partie.
 * 
 * @author Éric Wenaas
 * @version 0.40
 */
class DialogOptions extends javax.swing.JDialog {

    DialogOptions(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    String getTypeJoueur(Personnage personnage) {
        String reponse = "";
        switch (personnage) {
            case KONRAD:
                reponse =  getTypeJoueurKonrad();
                break;
            case LISAR:
                reponse =  getTypeJoueurLisar();
                break;
            case DELFADOR:
                reponse = getTypeJoueurDelfador();
                break;
        }
        return reponse;
    }
    
    boolean isSelectionCarte() {
        return butSelectionCarte.isSelected();
    }

    private String getTypeJoueurLisar() {
        String reponse = "Inactif";
        if (butHumainLisar.isSelected()) {
            reponse = "Humain";
        } else if (butAILisar.isSelected()) {
            reponse = "AI";
        }
        return reponse;
    }

    private String getTypeJoueurKonrad() {
        String reponse = "Inactif";
        if (butHumainKonrad.isSelected()) {
            reponse = "Humain";
        } else if (butAIKonrad.isSelected()) {
            reponse = "AI";
        }
        return reponse;
    }
    
    private String getTypeJoueurDelfador() {
    String reponse = "Inactif";
        if (butHumainDelfador.isSelected()) {
            reponse = "Humain";
        } else if (butAIDelfador.isSelected()) {
            reponse = "AI";
        }
        return reponse;
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butGroupKonrad = new javax.swing.ButtonGroup();
        butGroupLisar = new javax.swing.ButtonGroup();
        buttonDelfador = new javax.swing.ButtonGroup();
        labTitreOptiion = new javax.swing.JLabel();
        butInactifKonrad = new javax.swing.JRadioButton();
        butAILisar = new javax.swing.JRadioButton();
        butHumainKonrad = new javax.swing.JRadioButton();
        jbutOK = new javax.swing.JButton();
        butAIKonrad = new javax.swing.JRadioButton();
        labJoueurs = new javax.swing.JLabel();
        butInactifLisar = new javax.swing.JRadioButton();
        labLisar = new javax.swing.JLabel();
        labKonrad = new javax.swing.JLabel();
        butHumainLisar = new javax.swing.JRadioButton();
        butSelectionCarte = new javax.swing.JCheckBox();
        labDelfador = new javax.swing.JLabel();
        butHumainDelfador = new javax.swing.JRadioButton();
        butAIDelfador = new javax.swing.JRadioButton();
        butInactifDelfador = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labTitreOptiion.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        labTitreOptiion.setText("Options de configuration");

        butGroupKonrad.add(butInactifKonrad);
        butInactifKonrad.setText("Inactif");

        butGroupLisar.add(butAILisar);
        butAILisar.setSelected(true);
        butAILisar.setText("AI");

        butGroupKonrad.add(butHumainKonrad);
        butHumainKonrad.setSelected(true);
        butHumainKonrad.setText("Humain");

        jbutOK.setText("OK");
        jbutOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutOKActionPerformed(evt);
            }
        });

        butGroupKonrad.add(butAIKonrad);
        butAIKonrad.setText("AI");

        labJoueurs.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        labJoueurs.setText("Personnages");

        butGroupLisar.add(butInactifLisar);
        butInactifLisar.setText("Inactif");

        labLisar.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        labLisar.setText(Personnage.LISAR.getNom());

        labKonrad.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        labKonrad.setText(Personnage.KONRAD.getNom());

        butGroupLisar.add(butHumainLisar);
        butHumainLisar.setText("Humain");

        butSelectionCarte.setText("Sélectionner une carte");

        labDelfador.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        labDelfador.setText(Personnage.DELFADOR.getNom());

        buttonDelfador.add(butHumainDelfador);
        butHumainDelfador.setText("Humain");

        buttonDelfador.add(butAIDelfador);
        butAIDelfador.setSelected(true);
        butAIDelfador.setText("AI");

        buttonDelfador.add(butInactifDelfador);
        butInactifDelfador.setText("Inactif");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbutOK, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labTitreOptiion)
                            .addComponent(labJoueurs))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labKonrad)
                            .addComponent(labLisar)
                            .addComponent(labDelfador)
                            .addComponent(butSelectionCarte))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(butHumainLisar)
                                    .addComponent(butHumainKonrad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(butAILisar)
                                    .addComponent(butAIKonrad)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butHumainDelfador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(butAIDelfador)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butInactifDelfador)
                            .addComponent(butInactifLisar)
                            .addComponent(butInactifKonrad))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {butAIKonrad, butAILisar, butHumainKonrad, butHumainLisar, butInactifKonrad, butInactifLisar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTitreOptiion)
                .addGap(18, 18, 18)
                .addComponent(labJoueurs)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labKonrad)
                    .addComponent(butHumainKonrad)
                    .addComponent(butAIKonrad)
                    .addComponent(butInactifKonrad))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labLisar)
                    .addComponent(butInactifLisar)
                    .addComponent(butAILisar)
                    .addComponent(butHumainLisar))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labDelfador)
                    .addComponent(butHumainDelfador)
                    .addComponent(butAIDelfador)
                    .addComponent(butInactifDelfador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(butSelectionCarte)
                .addGap(2, 2, 2)
                .addComponent(jbutOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutOKActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jbutOKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton butAIDelfador;
    private javax.swing.JRadioButton butAIKonrad;
    private javax.swing.JRadioButton butAILisar;
    private javax.swing.ButtonGroup butGroupKonrad;
    private javax.swing.ButtonGroup butGroupLisar;
    private javax.swing.JRadioButton butHumainDelfador;
    private javax.swing.JRadioButton butHumainKonrad;
    private javax.swing.JRadioButton butHumainLisar;
    private javax.swing.JRadioButton butInactifDelfador;
    private javax.swing.JRadioButton butInactifKonrad;
    private javax.swing.JRadioButton butInactifLisar;
    private javax.swing.JCheckBox butSelectionCarte;
    private javax.swing.ButtonGroup buttonDelfador;
    private javax.swing.JButton jbutOK;
    private javax.swing.JLabel labDelfador;
    private javax.swing.JLabel labJoueurs;
    private javax.swing.JLabel labKonrad;
    private javax.swing.JLabel labLisar;
    private javax.swing.JLabel labTitreOptiion;
    // End of variables declaration//GEN-END:variables
}
