/*
 * Copyright (C) 2015 Éric Wenaas
 *
 */
package ca.qc.bdeb.hexknight.ui;

import ca.qc.bdeb.hexknight.commun.MomentJour;
import ca.qc.bdeb.hexknight.model.Partie;
import ca.qc.bdeb.hexknight.commun.Observateur;

/**
 *
 * @author Éric Wenaas
 */
public class PanelPartieInfo extends javax.swing.JPanel implements Observateur {

    private Partie modelePartie;

    /**
     * Creates new form PartieInfoPanel
     *
     * @param partie
     */
    public PanelPartieInfo(Partie partie) {
        initComponents();
        this.modelePartie = partie;
        modelePartie.ajouterObservateur(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labInfoTour = new javax.swing.JLabel();
        labInfoDerniereRonde = new javax.swing.JLabel();
        labInfoJour = new javax.swing.JLabel();

        setBackground(CouleursInterface.ZONE_INFO);

        labInfoTour.setBackground(CouleursInterface.ZONE_INFO);
        labInfoTour.setFont(PolicesInterface.policeGrande);
        labInfoTour.setForeground(new java.awt.Color(255, 255, 255));
        labInfoTour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labInfoTour.setText("TOUR: 1");

        labInfoDerniereRonde.setBackground(new java.awt.Color(0, 0, 0));
        labInfoDerniereRonde.setFont(PolicesInterface.policeNormale);
        labInfoDerniereRonde.setForeground(new java.awt.Color(255, 255, 255));
        labInfoDerniereRonde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labInfoDerniereRonde.setText("DERNIERE RONDE");

        labInfoJour.setBackground(CouleursInterface.ZONE_INFO);
        labInfoJour.setFont(PolicesInterface.policeGrande);
        labInfoJour.setForeground(new java.awt.Color(255, 255, 255));
        labInfoJour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labInfoJour.setText("JOUR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labInfoTour, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labInfoJour, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labInfoDerniereRonde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labInfoTour, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(labInfoJour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labInfoDerniereRonde, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labInfoDerniereRonde;
    private javax.swing.JLabel labInfoJour;
    private javax.swing.JLabel labInfoTour;
    // End of variables declaration//GEN-END:variables

    @Override
    public void changementEtat() {
        if (modelePartie.isPartieTerminee()) {
            labInfoTour.setText("");
            labInfoJour.setText("");
            labInfoDerniereRonde.setText("");
        } else {
            labInfoTour.setText("TOUR " + modelePartie.getNumeroTour());
           MomentJour moment = modelePartie.getPhaseJour();
            labInfoJour.setText(moment.toString());
            if (modelePartie.isDerniereRonde()) {
                labInfoDerniereRonde.setText("DERNIERE RONDE");
            } else {
                labInfoDerniereRonde.setText("");
            }
        }
        repaint();
    }

    @Override
    public void changementEtat(Enum<?> property, Object o) {
        changementEtat();
    }
}
