/*
 * Copyright (C) 2015 Éric Wenaas
 *
 */
package ca.qc.bdeb.hexknight.ui;

import ca.qc.bdeb.hexknight.commun.InfosJoueur;
import ca.qc.bdeb.hexknight.model.Joueur;
import ca.qc.bdeb.hexknight.commun.Observateur;

/**
 * Cette classe indique les informations sur les joueurs. Ce qui comprend notamment, le nombre de cartes
 * en main, l'armure, l'expérience, le détail des points, etc...
 *
 * @author Éric Wenaas
 * @version 0.40
 */
public class PanelJoueurInfo extends javax.swing.JPanel implements Observateur {

    private final Joueur modeleJoueur;
    /**
     * Ce Panel affiche les informations courantes sur le Joueur.
     * 
     * @param joueurObserve Le joueur que l'on observe
     */
    public PanelJoueurInfo(Joueur joueurObserve) {
        modeleJoueur = joueurObserve;
        joueurObserve.ajouterObservateur(this);
        initComponents();
        changementEtat();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        labTextCouleur = new javax.swing.JLabel();
        labInfoPersonnage = new javax.swing.JLabel();
        labTextArmure = new javax.swing.JLabel();
        labTextTailleMain = new javax.swing.JLabel();
        labTextNiveau = new javax.swing.JLabel();
        labInfoArmure = new javax.swing.JLabel();
        labInfoTailleMain = new javax.swing.JLabel();
        labInfoNiveau = new javax.swing.JLabel();
        labTextPoints = new javax.swing.JLabel();
        labInfoPoints = new javax.swing.JLabel();
        labTextTaillePaquet = new javax.swing.JLabel();
        labInfoTaillePaquet = new javax.swing.JLabel();
        labTextCartesEnMain = new javax.swing.JLabel();
        labInfoCartesEnMain = new javax.swing.JLabel();
        labTextExp = new javax.swing.JLabel();
        labTextCartes = new javax.swing.JLabel();
        labTextRuines = new javax.swing.JLabel();
        labInfoExp = new javax.swing.JLabel();
        labTextBlessures = new javax.swing.JLabel();
        labInfoCartes = new javax.swing.JLabel();
        labInfoRuines = new javax.swing.JLabel();
        labInfoBlessures = new javax.swing.JLabel();

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("0");

        setBackground(CouleursInterface.ZONE_INFO);

        labTextCouleur.setBackground(new java.awt.Color(0, 0, 0));
        labTextCouleur.setFont(PolicesInterface.policeNormale);
        labTextCouleur.setForeground(new java.awt.Color(255, 255, 255));
        labTextCouleur.setText("Nom du joueur:");

        labInfoPersonnage.setBackground(new java.awt.Color(0, 0, 0));
        labInfoPersonnage.setFont(PolicesInterface.policeNormale);
        labInfoPersonnage.setForeground(new java.awt.Color(255, 255, 255));
        labInfoPersonnage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labInfoPersonnage.setText("Bleu");

        labTextArmure.setBackground(new java.awt.Color(0, 0, 0));
        labTextArmure.setFont(PolicesInterface.policeNormale);
        labTextArmure.setForeground(new java.awt.Color(255, 255, 255));
        labTextArmure.setText("Armure:");

        labTextTailleMain.setBackground(new java.awt.Color(0, 0, 0));
        labTextTailleMain.setFont(PolicesInterface.policeNormale);
        labTextTailleMain.setForeground(new java.awt.Color(255, 255, 255));
        labTextTailleMain.setText("Base main:");

        labTextNiveau.setBackground(new java.awt.Color(0, 0, 0));
        labTextNiveau.setFont(PolicesInterface.policeNormale);
        labTextNiveau.setForeground(new java.awt.Color(255, 255, 255));
        labTextNiveau.setText("Prochain niveau:");

        labInfoArmure.setBackground(new java.awt.Color(0, 0, 0));
        labInfoArmure.setFont(PolicesInterface.policeNormale);
        labInfoArmure.setForeground(new java.awt.Color(255, 255, 255));
        labInfoArmure.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labInfoArmure.setText("2");

        labInfoTailleMain.setBackground(new java.awt.Color(0, 0, 0));
        labInfoTailleMain.setFont(PolicesInterface.policeNormale);
        labInfoTailleMain.setForeground(new java.awt.Color(255, 255, 255));
        labInfoTailleMain.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labInfoTailleMain.setText("5");

        labInfoNiveau.setBackground(new java.awt.Color(0, 0, 0));
        labInfoNiveau.setFont(PolicesInterface.policeNormale);
        labInfoNiveau.setForeground(new java.awt.Color(255, 255, 255));
        labInfoNiveau.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labInfoNiveau.setText("3");

        labTextPoints.setBackground(new java.awt.Color(0, 0, 0));
        labTextPoints.setFont(PolicesInterface.policeNormale);
        labTextPoints.setForeground(new java.awt.Color(255, 255, 255));
        labTextPoints.setText("Points:");

        labInfoPoints.setBackground(new java.awt.Color(0, 0, 0));
        labInfoPoints.setFont(PolicesInterface.policeNormale);
        labInfoPoints.setForeground(new java.awt.Color(255, 255, 255));
        labInfoPoints.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labInfoPoints.setText("0");

        labTextTaillePaquet.setBackground(new java.awt.Color(0, 0, 0));
        labTextTaillePaquet.setFont(PolicesInterface.policeNormale);
        labTextTaillePaquet.setForeground(new java.awt.Color(255, 255, 255));
        labTextTaillePaquet.setText("Taille paquet:");

        labInfoTaillePaquet.setBackground(new java.awt.Color(0, 0, 0));
        labInfoTaillePaquet.setFont(PolicesInterface.policeNormale);
        labInfoTaillePaquet.setForeground(new java.awt.Color(255, 255, 255));
        labInfoTaillePaquet.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labInfoTaillePaquet.setText("0");

        labTextCartesEnMain.setBackground(new java.awt.Color(0, 0, 0));
        labTextCartesEnMain.setFont(PolicesInterface.policeNormale);
        labTextCartesEnMain.setForeground(new java.awt.Color(255, 255, 255));
        labTextCartesEnMain.setText("Cartes en main:");

        labInfoCartesEnMain.setBackground(new java.awt.Color(0, 0, 0));
        labInfoCartesEnMain.setFont(PolicesInterface.policeNormale);
        labInfoCartesEnMain.setForeground(new java.awt.Color(255, 255, 255));
        labInfoCartesEnMain.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labInfoCartesEnMain.setText("5");

        labTextExp.setBackground(new java.awt.Color(0, 0, 0));
        labTextExp.setForeground(new java.awt.Color(255, 255, 255));
        labTextExp.setText("Expérience:");

        labTextCartes.setBackground(new java.awt.Color(0, 0, 0));
        labTextCartes.setForeground(new java.awt.Color(255, 255, 255));
        labTextCartes.setText("Cartes:");

        labTextRuines.setBackground(new java.awt.Color(0, 0, 0));
        labTextRuines.setForeground(new java.awt.Color(255, 255, 255));
        labTextRuines.setText("Ruines:");

        labInfoExp.setBackground(new java.awt.Color(0, 0, 0));
        labInfoExp.setForeground(new java.awt.Color(255, 255, 255));
        labInfoExp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labInfoExp.setText("0");

        labTextBlessures.setBackground(new java.awt.Color(0, 0, 0));
        labTextBlessures.setForeground(new java.awt.Color(255, 255, 255));
        labTextBlessures.setText("Blessures:");

        labInfoCartes.setBackground(new java.awt.Color(0, 0, 0));
        labInfoCartes.setForeground(new java.awt.Color(255, 255, 255));
        labInfoCartes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labInfoCartes.setText("0");

        labInfoRuines.setBackground(new java.awt.Color(0, 0, 0));
        labInfoRuines.setForeground(new java.awt.Color(255, 255, 255));
        labInfoRuines.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labInfoRuines.setText("0");

        labInfoBlessures.setBackground(new java.awt.Color(0, 0, 0));
        labInfoBlessures.setForeground(new java.awt.Color(255, 255, 255));
        labInfoBlessures.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labInfoBlessures.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labTextCouleur)
                    .addComponent(labTextArmure)
                    .addComponent(labTextTailleMain)
                    .addComponent(labTextCartesEnMain)
                    .addComponent(labTextTaillePaquet)
                    .addComponent(labTextPoints)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labTextNiveau)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labTextCartes)
                            .addComponent(labTextExp)
                            .addComponent(labTextRuines)
                            .addComponent(labTextBlessures))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labInfoNiveau, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addComponent(labInfoTaillePaquet, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addComponent(labInfoTailleMain, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addComponent(labInfoArmure, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addComponent(labInfoPersonnage, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addComponent(labInfoPoints, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addComponent(labInfoExp)
                        .addComponent(labInfoCartesEnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labInfoCartes)
                    .addComponent(labInfoRuines)
                    .addComponent(labInfoBlessures))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labInfoArmure, labInfoNiveau, labInfoPersonnage, labInfoPoints, labInfoTailleMain, labInfoTaillePaquet});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTextCouleur)
                    .addComponent(labInfoPersonnage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTextArmure)
                    .addComponent(labInfoArmure))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTextTailleMain)
                    .addComponent(labInfoTailleMain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTextCartesEnMain)
                    .addComponent(labInfoCartesEnMain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTextTaillePaquet)
                    .addComponent(labInfoTaillePaquet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTextNiveau)
                    .addComponent(labInfoNiveau))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTextPoints)
                    .addComponent(labInfoPoints))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTextExp)
                    .addComponent(labInfoExp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTextCartes, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labInfoCartes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTextRuines)
                    .addComponent(labInfoRuines))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTextBlessures)
                    .addComponent(labInfoBlessures))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labInfoArmure;
    private javax.swing.JLabel labInfoBlessures;
    private javax.swing.JLabel labInfoCartes;
    private javax.swing.JLabel labInfoCartesEnMain;
    private javax.swing.JLabel labInfoExp;
    private javax.swing.JLabel labInfoNiveau;
    private javax.swing.JLabel labInfoPersonnage;
    private javax.swing.JLabel labInfoPoints;
    private javax.swing.JLabel labInfoRuines;
    private javax.swing.JLabel labInfoTailleMain;
    private javax.swing.JLabel labInfoTaillePaquet;
    private javax.swing.JLabel labTextArmure;
    private javax.swing.JLabel labTextBlessures;
    private javax.swing.JLabel labTextCartes;
    private javax.swing.JLabel labTextCartesEnMain;
    private javax.swing.JLabel labTextCouleur;
    private javax.swing.JLabel labTextExp;
    private javax.swing.JLabel labTextNiveau;
    private javax.swing.JLabel labTextPoints;
    private javax.swing.JLabel labTextRuines;
    private javax.swing.JLabel labTextTailleMain;
    private javax.swing.JLabel labTextTaillePaquet;
    // End of variables declaration//GEN-END:variables

    @Override
    public final void changementEtat() {
        InfosJoueur infos = modeleJoueur.getInfosJoueur();
        labInfoPersonnage.setText(infos.nomPersonnage);
        labInfoArmure.setText(Integer.toString(infos.niveauArmure));
        labInfoTailleMain.setText(Integer.toString(infos.tailleMain));
        labInfoCartesEnMain.setText(Integer.toString(infos.carteEnMains));
        StringBuilder bufferExperience = new StringBuilder();
        bufferExperience.append(Integer.toString(infos.experience));
        bufferExperience.append("/");
        bufferExperience.append(Integer.toString(infos.prochainNiveau));
        labInfoNiveau.setText(bufferExperience.toString());
        labInfoPoints.setText(Integer.toString(infos.points));
        labInfoTaillePaquet.setText(Integer.toString(infos.taillePaquet));
        labInfoExp.setText(Integer.toString(infos.experience));
        labInfoBlessures.setText(Integer.toString(infos.ajustementBlessures));
        labInfoCartes.setText(Integer.toString(infos.ajustementCartes));
        labInfoRuines.setText(Integer.toString(infos.nombreRuines));
    }

    @Override
    public void changementEtat(Enum<?> property, Object o) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
